/***************************************************************************
 * This file is part of the cryptographic library CycurLIB                 *
 *                                                                         *
 * Copyright (C) 2016 ESCRYPT GmbH - All Rights Reserved                   *
 * www.escrypt.com                                                         *
 ***************************************************************************/

/***************************************************************************/
/*!
   \file

   \brief Whirlpool Selftest

   $Rev: 3832 $
 */
/***************************************************************************/

/***************************************************************************
 * 1. INCLUDES                                                             *
 ***************************************************************************/

#include "test_whirlpool.h"
#include "selftest.h"
#include "whirlpool.h"

/***************************************************************************
 * 2. DEFINES                                                              *
 ***************************************************************************/

/* Number of testcases for Whirlpool compliance test */
#define NUMBER_OF_WHIRLPOOL_TESTCASES 11U

/***************************************************************************
 * 3. DECLARATIONS                                                         *
 ***************************************************************************/
/* Whirlpool test vectors, first 8 taken from ISO, last 3 generated by reference implementation */
static const Esc_CHAR* const WP_MSG[NUMBER_OF_WHIRLPOOL_TESTCASES] =
{
    "",                         /* empty string */
    "a",                        /* one byte     */
    "abc",
    "message digest",
    "abcdefghijklmnopqrstuvwxyz",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
    "12345678901234567890123456789012345678901234567890123456789012345678901234567890",
    "abcdbcdecdefdefgefghfghighijhijk",
    "1234567890123456789012345678901234567890123456789012345678901234", /* one complete block */
    "123456789012345678901234567890123456789012345678901234567890123",  /* one byte missing to complete a block */
    "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890",   /* multiple blocks */
};


static Esc_ERROR
EscTstWhirlpool_Compliance(
    void );

static Esc_ERROR
EscTstWhirlpool_ComplianceSteps(
    void );

static Esc_ERROR
EscTstWhirlpool_StepsParams(
    void );

static Esc_ERROR
EscTstWhirlpool_FullParams(
    void );

static Esc_ERROR
EscTstWhirlpool_Truncation(
    void );

/***************************************************************************
 * 4. IMPLEMENTATION OF FUNCTIONS                                          *
 ***************************************************************************/

/**
\return Esc_NO_ERROR if everything works fine
*/
static Esc_ERROR
EscTstWhirlpool_Compliance(
    void )
{
    /* expected results after hashing, first 8 taken from ISO, last 3 generated by reference implementation */
    static const Esc_UINT8 WP_RES[NUMBER_OF_WHIRLPOOL_TESTCASES][EscWhirlpool_DIGEST_LEN] =
    {
        {
            0x19U, 0xFAU, 0x61U, 0xD7U, 0x55U, 0x22U, 0xA4U, 0x66U,
            0x9BU, 0x44U, 0xE3U, 0x9CU, 0x1DU, 0x2EU, 0x17U, 0x26U,
            0xC5U, 0x30U, 0x23U, 0x21U, 0x30U, 0xD4U, 0x07U, 0xF8U,
            0x9AU, 0xFEU, 0xE0U, 0x96U, 0x49U, 0x97U, 0xF7U, 0xA7U,
            0x3EU, 0x83U, 0xBEU, 0x69U, 0x8BU, 0x28U, 0x8FU, 0xEBU,
            0xCFU, 0x88U, 0xE3U, 0xE0U, 0x3CU, 0x4FU, 0x07U, 0x57U,
            0xEAU, 0x89U, 0x64U, 0xE5U, 0x9BU, 0x63U, 0xD9U, 0x37U,
            0x08U, 0xB1U, 0x38U, 0xCCU, 0x42U, 0xA6U, 0x6EU, 0xB3U
        },   /* "" */
        {
            0x8AU, 0xCAU, 0x26U, 0x02U, 0x79U, 0x2AU, 0xECU, 0x6FU,
            0x11U, 0xA6U, 0x72U, 0x06U, 0x53U, 0x1FU, 0xB7U, 0xD7U,
            0xF0U, 0xDFU, 0xF5U, 0x94U, 0x13U, 0x14U, 0x5EU, 0x69U,
            0x73U, 0xC4U, 0x50U, 0x01U, 0xD0U, 0x08U, 0x7BU, 0x42U,
            0xD1U, 0x1BU, 0xC6U, 0x45U, 0x41U, 0x3AU, 0xEFU, 0xF6U,
            0x3AU, 0x42U, 0x39U, 0x1AU, 0x39U, 0x14U, 0x5AU, 0x59U,
            0x1AU, 0x92U, 0x20U, 0x0DU, 0x56U, 0x01U, 0x95U, 0xE5U,
            0x3BU, 0x47U, 0x85U, 0x84U, 0xFDU, 0xAEU, 0x23U, 0x1AU
        },   /* "a" */
        {
            0x4EU, 0x24U, 0x48U, 0xA4U, 0xC6U, 0xF4U, 0x86U, 0xBBU,
            0x16U, 0xB6U, 0x56U, 0x2CU, 0x73U, 0xB4U, 0x02U, 0x0BU,
            0xF3U, 0x04U, 0x3EU, 0x3AU, 0x73U, 0x1BU, 0xCEU, 0x72U,
            0x1AU, 0xE1U, 0xB3U, 0x03U, 0xD9U, 0x7EU, 0x6DU, 0x4CU,
            0x71U, 0x81U, 0xEEU, 0xBDU, 0xB6U, 0xC5U, 0x7EU, 0x27U,
            0x7DU, 0x0EU, 0x34U, 0x95U, 0x71U, 0x14U, 0xCBU, 0xD6U,
            0xC7U, 0x97U, 0xFCU, 0x9DU, 0x95U, 0xD8U, 0xB5U, 0x82U,
            0xD2U, 0x25U, 0x29U, 0x20U, 0x76U, 0xD4U, 0xEEU, 0xF5U
        },   /* "abc" */
        {
            0x37U, 0x8CU, 0x84U, 0xA4U, 0x12U, 0x6EU, 0x2DU, 0xC6U,
            0xE5U, 0x6DU, 0xCCU, 0x74U, 0x58U, 0x37U, 0x7AU, 0xACU,
            0x83U, 0x8DU, 0x00U, 0x03U, 0x22U, 0x30U, 0xF5U, 0x3CU,
            0xE1U, 0xF5U, 0x70U, 0x0CU, 0x0FU, 0xFBU, 0x4DU, 0x3BU,
            0x84U, 0x21U, 0x55U, 0x76U, 0x59U, 0xEFU, 0x55U, 0xC1U,
            0x06U, 0xB4U, 0xB5U, 0x2AU, 0xC5U, 0xA4U, 0xAAU, 0xA6U,
            0x92U, 0xEDU, 0x92U, 0x00U, 0x52U, 0x83U, 0x8FU, 0x33U,
            0x62U, 0xE8U, 0x6DU, 0xBDU, 0x37U, 0xA8U, 0x90U, 0x3EU
        },   /* "message digest" */
        {
            0xF1U, 0xD7U, 0x54U, 0x66U, 0x26U, 0x36U, 0xFFU, 0xE9U,
            0x2CU, 0x82U, 0xEBU, 0xB9U, 0x21U, 0x2AU, 0x48U, 0x4AU,
            0x8DU, 0x38U, 0x63U, 0x1EU, 0xADU, 0x42U, 0x38U, 0xF5U,
            0x44U, 0x2EU, 0xE1U, 0x3BU, 0x80U, 0x54U, 0xE4U, 0x1BU,
            0x08U, 0xBFU, 0x2AU, 0x92U, 0x51U, 0xC3U, 0x0BU, 0x6AU,
            0x0BU, 0x8AU, 0xAEU, 0x86U, 0x17U, 0x7AU, 0xB4U, 0xA6U,
            0xF6U, 0x8FU, 0x67U, 0x3EU, 0x72U, 0x07U, 0x86U, 0x5DU,
            0x5DU, 0x98U, 0x19U, 0xA3U, 0xDBU, 0xA4U, 0xEBU, 0x3BU
        },   /* "abcdefghijklmnopqrstuvwxyz" */
        {
            0xDCU, 0x37U, 0xE0U, 0x08U, 0xCFU, 0x9EU, 0xE6U, 0x9BU,
            0xF1U, 0x1FU, 0x00U, 0xEDU, 0x9AU, 0xBAU, 0x26U, 0x90U,
            0x1DU, 0xD7U, 0xC2U, 0x8CU, 0xDEU, 0xC0U, 0x66U, 0xCCU,
            0x6AU, 0xF4U, 0x2EU, 0x40U, 0xF8U, 0x2FU, 0x3AU, 0x1EU,
            0x08U, 0xEBU, 0xA2U, 0x66U, 0x29U, 0x12U, 0x9DU, 0x8FU,
            0xB7U, 0xCBU, 0x57U, 0x21U, 0x1BU, 0x92U, 0x81U, 0xA6U,
            0x55U, 0x17U, 0xCCU, 0x87U, 0x9DU, 0x7BU, 0x96U, 0x21U,
            0x42U, 0xC6U, 0x5FU, 0x5AU, 0x7AU, 0xF0U, 0x14U, 0x67U
        },   /* "ABCDEFGHIJKLMNO..." */
        {
            0x46U, 0x6EU, 0xF1U, 0x8BU, 0xABU, 0xB0U, 0x15U, 0x4DU,
            0x25U, 0xB9U, 0xD3U, 0x8AU, 0x64U, 0x14U, 0xF5U, 0xC0U,
            0x87U, 0x84U, 0x37U, 0x2BU, 0xCCU, 0xB2U, 0x04U, 0xD6U,
            0x54U, 0x9CU, 0x4AU, 0xFAU, 0xDBU, 0x60U, 0x14U, 0x29U,
            0x4DU, 0x5BU, 0xD8U, 0xDFU, 0x2AU, 0x6CU, 0x44U, 0xE5U,
            0x38U, 0xCDU, 0x04U, 0x7BU, 0x26U, 0x81U, 0xA5U, 0x1AU,
            0x2CU, 0x60U, 0x48U, 0x1EU, 0x88U, 0xC5U, 0xA2U, 0x0BU,
            0x2CU, 0x2AU, 0x80U, 0xCFU, 0x3AU, 0x9AU, 0x08U, 0x3BU
        },   /* "123456789012345..." */
        {
            0x2AU, 0x98U, 0x7EU, 0xA4U, 0x0FU, 0x91U, 0x70U, 0x61U,
            0xF5U, 0xD6U, 0xF0U, 0xA0U, 0xE4U, 0x64U, 0x4FU, 0x48U,
            0x8AU, 0x7AU, 0x5AU, 0x52U, 0xDEU, 0xEEU, 0x65U, 0x62U,
            0x07U, 0xC5U, 0x62U, 0xF9U, 0x88U, 0xE9U, 0x5CU, 0x69U,
            0x16U, 0xBDU, 0xC8U, 0x03U, 0x1BU, 0xC5U, 0xBEU, 0x1BU,
            0x7BU, 0x94U, 0x76U, 0x39U, 0xFEU, 0x05U, 0x0BU, 0x56U,
            0x93U, 0x9BU, 0xAAU, 0xA0U, 0xADU, 0xFFU, 0x9AU, 0xE6U,
            0x74U, 0x5BU, 0x7BU, 0x18U, 0x1CU, 0x3BU, 0xE3U, 0xFDU
        },   /* "abcdbcdecdefdef..." */
        {
            0xA8U, 0xE0U, 0xE6U, 0x33U, 0x25U, 0xE5U, 0x5DU, 0xCBU,
            0x81U, 0x5AU, 0xEFU, 0x1EU, 0x2CU, 0x89U, 0x33U, 0x16U,
            0x30U, 0xDEU, 0x4DU, 0xE2U, 0x87U, 0x11U, 0x8BU, 0x22U,
            0x0CU, 0xE5U, 0x67U, 0xB8U, 0x9AU, 0x6AU, 0x28U, 0x64U,
            0x16U, 0xC7U, 0xA0U, 0x48U, 0xF8U, 0xB8U, 0x9CU, 0x78U,
            0xA3U, 0xC5U, 0xDEU, 0x19U, 0x43U, 0xE9U, 0xE8U, 0x83U,
            0x26U, 0xFBU, 0xB7U, 0x45U, 0x32U, 0x1BU, 0x3CU, 0xA1U,
            0x67U, 0x61U, 0xB2U, 0x3EU, 0x6CU, 0x92U, 0x41U, 0x3DU
        },   /* one complete block */
        {
            0xDEU, 0xCBU, 0x27U, 0xC3U, 0x57U, 0x01U, 0x81U, 0x4CU,
            0xF7U, 0x3CU, 0x6FU, 0x1FU, 0xCDU, 0xDDU, 0x5EU, 0xA9U,
            0x25U, 0xB4U, 0x48U, 0x33U, 0x6DU, 0xD7U, 0xBAU, 0xE6U,
            0xD3U, 0xBCU, 0x0BU, 0xEDU, 0x1EU, 0x3FU, 0x48U, 0x62U,
            0xBAU, 0x6AU, 0xEBU, 0x66U, 0x5DU, 0x8EU, 0x5FU, 0x64U,
            0x59U, 0xD8U, 0x7AU, 0xEEU, 0xDEU, 0x07U, 0x01U, 0x81U,
            0xF9U, 0x1CU, 0x4CU, 0x90U, 0x64U, 0xBAU, 0x36U, 0xD8U,
            0xA8U, 0x4FU, 0xD1U, 0x82U, 0xDBU, 0xEAU, 0xC0U, 0x48U
        },   /* one byte missing to complete a block */
        {
            0x5EU, 0xEFU, 0x1AU, 0x45U, 0x83U, 0xA0U, 0xA4U, 0x88U,
            0x18U, 0xD7U, 0x86U, 0x01U, 0x28U, 0x31U, 0xB2U, 0x28U,
            0x66U, 0x56U, 0x43U, 0x64U, 0xF2U, 0x4FU, 0xC0U, 0x33U,
            0xB2U, 0xF8U, 0x63U, 0x43U, 0x0EU, 0xDAU, 0xEEU, 0x5FU,
            0x11U, 0x7BU, 0xDBU, 0x46U, 0xC6U, 0x80U, 0x22U, 0xD6U,
            0xEBU, 0x9AU, 0x66U, 0xD4U, 0x15U, 0x9EU, 0xA4U, 0x6BU,
            0x97U, 0x26U, 0x3EU, 0xCEU, 0xEAU, 0x4EU, 0x4AU, 0xBDU,
            0xE3U, 0xF3U, 0x8FU, 0xB7U, 0xCCU, 0x23U, 0x58U, 0x18U
        },   /* multiple blocks */
    };

    Esc_UINT8 i;
    Esc_ERROR returnCode = Esc_NO_ERROR;
    EscWhirlpool_ContextT wp_ctx;   /* hashing context */
    Esc_UINT8 wp_hash[EscWhirlpool_DIGEST_LEN] = { 0U };   /* hash value      */

    EscTst_PrintString( "Whirlpool Compliance test\n" );

    for (i = 0U; (i < NUMBER_OF_WHIRLPOOL_TESTCASES) && (returnCode == Esc_NO_ERROR); i++)
    {
        returnCode = EscWhirlpool_Init( &wp_ctx );

        if (returnCode == Esc_NO_ERROR)
        {
            const Esc_UINT8* message;
            Esc_UINT32 dataLen;

            EscTst_PrintString( "Message: \"" );
            EscTst_PrintString( WP_MSG[i] );
            EscTst_PrintString( "\" \n" );

            dataLen = EscTst_Strlen( WP_MSG[i] );
            if (dataLen == 0U)
            {
                message = Esc_NULL_PTR;
            }
            else
            {
                message = (const Esc_UINT8*)WP_MSG[i];
            }

            returnCode = EscWhirlpool_Update( &wp_ctx, message, dataLen );
        }

        if (returnCode == Esc_NO_ERROR)
        {
            returnCode = EscWhirlpool_Finish( &wp_ctx, wp_hash, EscWhirlpool_DIGEST_LEN );
        }

        if (returnCode == Esc_NO_ERROR)
        {
            /* compare results */
            EscTst_PrintArray( "Expected result", WP_RES[i], EscWhirlpool_DIGEST_LEN );

            EscTst_PrintArray( "Received result", wp_hash, EscWhirlpool_DIGEST_LEN );
            if ( EscTst_Memcmp( wp_hash, WP_RES[i], EscWhirlpool_DIGEST_LEN ) )
            {
                EscTst_PrintString( "Correct\n\n\n" );
            }
            else
            {
                EscTst_PrintString( "FAILED!!!\n\n\n" );
                returnCode = Esc_KAT_FAILED;
            }
        }
    }

    return returnCode;
}

/**
\return Esc_NO_ERROR if everything works fine
*/
static Esc_ERROR
EscTstWhirlpool_ComplianceSteps(
    void )
{
    /* A long test vector */
    static const Esc_CHAR WP_MSG_LONG[] =
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

    static const Esc_UINT8 WP_RES_LONG[EscWhirlpool_DIGEST_LEN] =
    {
        0xF0U, 0xA7U, 0xC9U, 0xFBU, 0x95U, 0xACU, 0x32U, 0xC9U,
        0xEEU, 0x97U, 0x80U, 0x80U, 0xA1U, 0x37U, 0xEAU, 0xA7U,
        0xAEU, 0x91U, 0x3DU, 0xDEU, 0xEDU, 0x73U, 0xE7U, 0x2FU,
        0x43U, 0x22U, 0x42U, 0x0DU, 0x89U, 0x4DU, 0x92U, 0x3EU,
        0xCDU, 0xF6U, 0x4AU, 0x38U, 0x50U, 0x20U, 0xD1U, 0xB0U,
        0x02U, 0xDDU, 0x6DU, 0x79U, 0x5DU, 0x59U, 0xAEU, 0xE4U,
        0xE7U, 0x85U, 0xAFU, 0xAFU, 0x1AU, 0xFAU, 0xFDU, 0xBAU,
        0x57U, 0xE0U, 0x69U, 0x55U, 0x36U, 0x8BU, 0x24U, 0x87U
    };

    Esc_ERROR returnCode;
    EscWhirlpool_ContextT wp_ctx;   /* hashing context */
    Esc_UINT8 wp_hash[EscWhirlpool_DIGEST_LEN] = { 0U };   /* hash value      */

    EscTst_PrintString( "Whirlpool ComplianceSteps test\n" );

    returnCode = EscWhirlpool_Init( &wp_ctx );

    if (returnCode == Esc_NO_ERROR)
    {
        EscTst_PrintString( "Message: \"" );
        EscTst_PrintString( WP_MSG_LONG );
        EscTst_PrintString( "\"\n" );
        EscTst_PrintString( "EscWhirlpool_Update (First 70 bytes)\n" );
        returnCode = EscWhirlpool_Update( &wp_ctx, (const Esc_UINT8*)WP_MSG_LONG, 70U );
    }

    if (returnCode == Esc_NO_ERROR)
    {
        EscTst_PrintString( "EscWhirlpool_Update (Remaining bytes)\n" );
        returnCode = EscWhirlpool_Update( &wp_ctx, (const Esc_UINT8*)&WP_MSG_LONG[70], EscTst_Strlen( WP_MSG_LONG ) - 70U );
    }

    if (returnCode == Esc_NO_ERROR)
    {
        returnCode = EscWhirlpool_Finish( &wp_ctx, wp_hash, EscWhirlpool_DIGEST_LEN );
    }

    if (returnCode == Esc_NO_ERROR)
    {
        /* compare results */
        EscTst_PrintArray( "Expected returnCode", WP_RES_LONG, EscWhirlpool_DIGEST_LEN );
        EscTst_PrintArray( "Received returnCode", wp_hash, EscWhirlpool_DIGEST_LEN );

        if ( EscTst_Memcmp( wp_hash, WP_RES_LONG, EscWhirlpool_DIGEST_LEN ) )
        {
            EscTst_PrintString( "Correct\n\n\n" );
        }
        else
        {
            EscTst_PrintString( "FAILED!!!\n\n\n" );
            returnCode = Esc_KAT_FAILED;
        }
    }

    return returnCode;
}

static Esc_ERROR
EscTstWhirlpool_StepsParams(
    void )
{
    Esc_ERROR returnCode;
    const Esc_UINT8* msg;
    Esc_UINT32 msgLen;
    EscWhirlpool_ContextT wp_ctx;   /* hashing context */
    Esc_UINT8 wp_hash[EscWhirlpool_DIGEST_LEN] = { 0U };   /* hash value */

    msg = (const Esc_UINT8*)WP_MSG[1];
    msgLen = EscTst_Strlen( WP_MSG[1] );

    EscTst_PrintString( "EscWhirlpool_Init() with ctx==0\n" );
    returnCode = EscWhirlpool_Init( Esc_NULL_PTR );
    returnCode = EscTst_CheckResultFailed( &returnCode, Esc_NULL_POINTER_ERROR );

    if (returnCode == Esc_NO_ERROR)
    {
        EscTst_PrintString( "EscWhirlpool_Update() with ctx==0\n" );
        returnCode = EscWhirlpool_Update( Esc_NULL_PTR, msg, msgLen );
        returnCode = EscTst_CheckResultFailed( &returnCode, Esc_NULL_POINTER_ERROR );

        if (returnCode == Esc_NO_ERROR)
        {
            EscTst_PrintString( "EscWhirlpool_Update() with chunk_data==0 and chunk_length>0\n" );
            returnCode = EscWhirlpool_Update( &wp_ctx, Esc_NULL_PTR, 1U );
            returnCode = EscTst_CheckResultFailed( &returnCode, Esc_NULL_POINTER_ERROR );
        }
    }

    if (returnCode == Esc_NO_ERROR)
    {
        EscTst_PrintString( "EscWhirlpool_Finish() with ctx==0\n" );
        returnCode = EscWhirlpool_Finish( Esc_NULL_PTR, wp_hash, EscWhirlpool_DIGEST_LEN );
        returnCode = EscTst_CheckResultFailed( &returnCode, Esc_NULL_POINTER_ERROR );

        if (returnCode == Esc_NO_ERROR)
        {
            EscTst_PrintString( "EscWhirlpool_Finish() with wp_hash==0\n" );
            returnCode = EscWhirlpool_Finish( &wp_ctx, Esc_NULL_PTR, EscWhirlpool_DIGEST_LEN );
            returnCode = EscTst_CheckResultFailed( &returnCode, Esc_NULL_POINTER_ERROR );
            if (returnCode == Esc_NO_ERROR)
            {
                EscTst_PrintString( "EscWhirlpool_Finish() with digestLength==0\n" );
                returnCode = EscWhirlpool_Finish( &wp_ctx, wp_hash, 0U );
                returnCode = EscTst_CheckResultFailed( &returnCode, Esc_INVALID_PARAMETER );
                if ( returnCode == Esc_NO_ERROR)
                {
                    EscTst_PrintString( "EscWhirlpool_Finish() with digestLength > EscWhirlpool_DIGEST_LEN\n" );
                    returnCode = EscWhirlpool_Finish( &wp_ctx, wp_hash, (Esc_UINT8)(EscWhirlpool_DIGEST_LEN+1U) );
                    returnCode = EscTst_CheckResultFailed( &returnCode, Esc_INVALID_PARAMETER );
                }
            }
        }
    }

    return returnCode;
}

static Esc_ERROR
EscTstWhirlpool_FullParams(
    void )
{
    Esc_ERROR returnCode;
    const Esc_UINT8* msg;
    Esc_UINT32 msgLen;
    Esc_UINT8 wp_hash[EscWhirlpool_DIGEST_LEN] = { 0U };   /* hash value */

    msg = (const Esc_UINT8*)WP_MSG[1];
    msgLen = EscTst_Strlen( WP_MSG[1] );

    EscTst_PrintString( "EscWhirlpool_Calc() with message==0 and dataLen>0\n" );
    returnCode = EscWhirlpool_Calc( Esc_NULL_PTR, 1U, wp_hash, EscWhirlpool_DIGEST_LEN );
    returnCode = EscTst_CheckResultFailed( &returnCode, Esc_NULL_POINTER_ERROR );

    if (returnCode == Esc_NO_ERROR)
    {
        EscTst_PrintString( "EscWhirlpool_Calc() with wp_hash==0\n" );
        returnCode = EscWhirlpool_Calc( msg, msgLen, Esc_NULL_PTR, EscWhirlpool_DIGEST_LEN );
        returnCode = EscTst_CheckResultFailed( &returnCode, Esc_NULL_POINTER_ERROR );
    }

    return returnCode;
}

static Esc_ERROR
EscTstWhirlpool_Truncation(
    void )
{
    static const Esc_CHAR* WP_MSG_Truncation = "abcdefghijklmnopqrstuvwxyz";
    static const Esc_UINT8 digestLengths[] =
    {
        /* Smallest possible lengths */
        1U, 2U, 3U, 4U,

        /* Highest possible lengths */
        (Esc_UINT8)(EscWhirlpool_DIGEST_LEN - 4U),
        (Esc_UINT8)(EscWhirlpool_DIGEST_LEN - 3U),
        (Esc_UINT8)(EscWhirlpool_DIGEST_LEN - 2U),
        (Esc_UINT8)(EscWhirlpool_DIGEST_LEN - 1U)
    };

    Esc_UINT32 numDigestLengths = sizeof(digestLengths) / sizeof(digestLengths[0]);

    Esc_UINT8 WP_RES_Truncation[EscWhirlpool_DIGEST_LEN];
    Esc_ERROR returnCode = Esc_NO_ERROR;
    EscWhirlpool_ContextT wp_ctx;   /* hashing context */
    Esc_UINT8 zeroArray[EscWhirlpool_DIGEST_LEN];
    Esc_UINT8 wp_hash[EscWhirlpool_DIGEST_LEN] = { 0U };   /* hash value      */
    Esc_UINT8 i, j;

    for (i = 0U; (i < numDigestLengths) && (returnCode == Esc_NO_ERROR); i++)
    {
        Esc_UINT8 digestLength = digestLengths[i];

        for (j = 0U; j < EscWhirlpool_DIGEST_LEN; j++)
        {
            zeroArray[j] = 0U;
            wp_hash[j] = 0U;
        }

        returnCode = EscWhirlpool_Calc((const Esc_UINT8*)WP_MSG_Truncation, EscTst_Strlen( WP_MSG_Truncation ), WP_RES_Truncation, EscWhirlpool_DIGEST_LEN );

        EscTst_PrintString( "Whirlpool Truncation test\n" );
        if ( returnCode == Esc_NO_ERROR )
        {
            returnCode = EscWhirlpool_Init( &wp_ctx );
        }

        if (returnCode == Esc_NO_ERROR)
        {
            EscTst_PrintString( "Message: \"" );
            EscTst_PrintString( WP_MSG_Truncation );
            EscTst_PrintString( "\"\n" );
            returnCode = EscWhirlpool_Update( &wp_ctx, (const Esc_UINT8*)WP_MSG_Truncation, EscTst_Strlen( WP_MSG_Truncation ) );
        }

        if (returnCode == Esc_NO_ERROR)
        {
            returnCode = EscWhirlpool_Finish( &wp_ctx, wp_hash, digestLength );
        }

        if (returnCode == Esc_NO_ERROR)
        {
            /* compare results */
            EscTst_PrintArray( "Expected digest", WP_RES_Truncation, (Esc_UINT32)digestLength );
            EscTst_PrintArray( "Received digest", wp_hash, (Esc_UINT32)digestLength );

            if ( EscTst_Memcmp( wp_hash, WP_RES_Truncation, (Esc_UINT32)digestLength ) )
            {
                if ( EscTst_Memcmp( &wp_hash[digestLength], &zeroArray[digestLength], EscWhirlpool_DIGEST_LEN - (Esc_UINT32)digestLength ) )
                {
                    EscTst_PrintString( "Correct\n\n\n" );
                }
                else
                {
                    EscTst_PrintString( "FAILED truncation!!!\n\n\n" );
                    returnCode = Esc_KAT_FAILED;
                }
            }
            else
            {
                EscTst_PrintString( "FAILED!!!\n\n\n" );
                returnCode = Esc_KAT_FAILED;
            }
        }
    }

    return returnCode;
}


Esc_ERROR
EscTstWhirlpool_Perform(
    void )
{
    Esc_ERROR returnCode;

    returnCode = EscTstWhirlpool_Compliance();
    if (returnCode == Esc_NO_ERROR)
    {
        returnCode = EscTstWhirlpool_ComplianceSteps();
    }

    if (returnCode == Esc_NO_ERROR)
    {
        returnCode = EscTstWhirlpool_StepsParams();
    }

    if (returnCode == Esc_NO_ERROR)
    {
        returnCode = EscTstWhirlpool_FullParams();
    }

    if (returnCode == Esc_NO_ERROR)
    {
        returnCode = EscTstWhirlpool_Truncation();
    }

    return returnCode;
}

/***************************************************************************
 * 6. END                                                                  *
 ***************************************************************************/
