/***************************************************************************
 * This file is part of the cryptographic library CycurLIB                 *
 *                                                                         *
 * Copyright (C) 2016 ESCRYPT GmbH - All Rights Reserved                   *
 * www.escrypt.com                                                         *
 ***************************************************************************/

/***************************************************************************/
/*!
\file

\brief       ECC key derivation function

\see  NIST SP 800-56Ar2, specifically section 5.8


*/
/***************************************************************************/

#ifndef ESC_ECC_KDF_H_
#define ESC_ECC_KDF_H_


#ifdef  __cplusplus
extern "C" {
#endif  /*end c plus plus if*/

/***************************************************************************
* 1. INCLUDES                                                              *
****************************************************************************/
#include "sha_256.h"
#include "mem_mgt.h"

/***************************************************************************
* 2. DEFINES REQUIRED BY CONFIGURATION (MUST NOT BE CHANGED!)             *
***************************************************************************/

/***************************************************************************
* 3. CONFIGURATION                                                        *
***************************************************************************/

/***************************************************************************
* 4. DEFINES                                                              *
***************************************************************************/

/***************************************************************************
* 6. FUNCTION PROTOTYPES                                                  *
***************************************************************************/

/**
this function generates a key according to the NIST 800 56Ar2 key derivation function using SHA256

\note : max size of input data (zLength + otherInfoLength) cannot exceed max of 32-bit unsigned int, 2^32 -1

\param[out] key : pointer to byte array to hold key generated by this function
\param[in] keySize : Size in bytes of the key to be generated
\param[in] z : pointer to shared secret data byte array
\param[in] zLength : length in bytes of z array
\param[in] otherInfo : pointer to byte array of additional info for key derivation
\param[in] otherInfoLength : size in bytes of the otherInfo byte array

\return 0 Esc_NO_ERROR on success, !0 on failure
*/
Esc_ERROR
EscEccKdf_Generate(
    Esc_UINT8 *key,
    Esc_UINT32 keySize,
    const Esc_UINT8 *z,
    const Esc_UINT32 zLength,
    const Esc_UINT8 *otherInfo,
    const Esc_UINT32 otherInfoLength);



#ifdef  __cplusplus
}
#endif  /*end c plus plus if*/

#endif /*end ESC_ECC_KDF_H_ if*/
/***************************************************************************
* 7. END                                                                  *
***************************************************************************/
